# Form implementation generated from reading ui file 'tev_main_window_6.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Trigonometry_Equation_Visualizer(object):
    def setupUi(self, Trigonometry_Equation_Visualizer):
        Trigonometry_Equation_Visualizer.setObjectName("Trigonometry_Equation_Visualizer")
        Trigonometry_Equation_Visualizer.resize(1280, 870)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Trigonometry_Equation_Visualizer.sizePolicy().hasHeightForWidth())
        Trigonometry_Equation_Visualizer.setSizePolicy(sizePolicy)
        Trigonometry_Equation_Visualizer.setMinimumSize(QtCore.QSize(1240, 850))
        Trigonometry_Equation_Visualizer.setMaximumSize(QtCore.QSize(1280, 870))
        Trigonometry_Equation_Visualizer.setStyleSheet("/*The Main Window Style*/\n"
"background-color:#232222;\n"
"font-family: Verdana;")
        self.TEV_main_centeral_widget = QtWidgets.QWidget(parent=Trigonometry_Equation_Visualizer)
        self.TEV_main_centeral_widget.setObjectName("TEV_main_centeral_widget")
        self.TEV_stackedWidget = QtWidgets.QStackedWidget(parent=self.TEV_main_centeral_widget)
        self.TEV_stackedWidget.setGeometry(QtCore.QRect(9, 9, 1261, 861))
        self.TEV_stackedWidget.setObjectName("TEV_stackedWidget")
        self.TEV_Main_page = QtWidgets.QWidget()
        self.TEV_Main_page.setObjectName("TEV_Main_page")
        self.TEV_title_label = QtWidgets.QLabel(parent=self.TEV_Main_page)
        self.TEV_title_label.setGeometry(QtCore.QRect(430, 10, 821, 91))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(True)
        self.TEV_title_label.setFont(font)
        self.TEV_title_label.setStyleSheet("/*Main Text edit Stuff */\n"
"background-color: #6C84E8;\n"
"color: #1A2329;\n"
"\n"
"/*Font Stuff */\n"
"font-weight: 1000px;\n"
"font-size: 20px;\n"
"font-family: Verdana;\n"
"\n"
"/*Border Stuff */\n"
"border: 2px solid rgb(33, 37, 43);\n"
"border-radius: 10px;")
        self.TEV_title_label.setObjectName("TEV_title_label")
        self.TEV_equation1_lineEdit = QtWidgets.QLineEdit(parent=self.TEV_Main_page)
        self.TEV_equation1_lineEdit.setGeometry(QtCore.QRect(20, 20, 381, 51))
        self.TEV_equation1_lineEdit.setStyleSheet("/*Main Text edit Stuff */\n"
"background-color: #5B754C;\n"
"color: black;\n"
"\n"
"/*Font Stuff */\n"
"font-weight: 1000px;\n"
"font-size: 21px;\n"
"font-family: Verdana;\n"
"\n"
"/*Border Stuff */\n"
"border: 2px solid rgb(33, 37, 43);\n"
"border-radius: 10px;")
        self.TEV_equation1_lineEdit.setText("")
        self.TEV_equation1_lineEdit.setObjectName("TEV_equation1_lineEdit")
        self.TEV_background_style_btn_label = QtWidgets.QLabel(parent=self.TEV_Main_page)
        self.TEV_background_style_btn_label.setGeometry(QtCore.QRect(420, 130, 831, 71))
        self.TEV_background_style_btn_label.setStyleSheet("/*Main Text edit Stuff */\n"
"background-color: #4C504B;\n"
"color: black;\n"
"\n"
"/*Font Stuff */\n"
"font-weight: 1000px;\n"
"font-size: 18px;\n"
"font-family: Verdana;\n"
"\n"
"/*Border Stuff */\n"
"border: 2px solid rgb(33, 37, 43);\n"
"border-radius: 15px;")
        self.TEV_background_style_btn_label.setText("")
        self.TEV_background_style_btn_label.setObjectName("TEV_background_style_btn_label")
        self.TEV_help_btn = QtWidgets.QPushButton(parent=self.TEV_Main_page)
        self.TEV_help_btn.setGeometry(QtCore.QRect(650, 120, 221, 71))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(13)
        font.setBold(True)
        self.TEV_help_btn.setFont(font)
        self.TEV_help_btn.setStyleSheet("/*Main Text edit Stuff */\n"
"background-color: #FFD95D;\n"
"color: #191818;\n"
"\n"
"/*Font Stuff */\n"
"font-weight: 500px;\n"
"font-family: Verdana;\n"
"\n"
"/*Border Stuff */\n"
"border: 2px solid rgb(33, 37, 43);\n"
"border-radius: 10px;")
        self.TEV_help_btn.setObjectName("TEV_help_btn")
        self.TEV_Divide_Radiobutton = QtWidgets.QRadioButton(parent=self.TEV_Main_page)
        self.TEV_Divide_Radiobutton.setGeometry(QtCore.QRect(1160, 120, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(-1)
        font.setBold(True)
        self.TEV_Divide_Radiobutton.setFont(font)
        self.TEV_Divide_Radiobutton.setStyleSheet("/*Main Text edit Stuff */\n"
"background-color: #F56D36;\n"
"color: #1A2329;\n"
"\n"
"/*Font Stuff */\n"
"font-weight: 1000px;\n"
"font-size: 17px;\n"
"font-family: Verdana;\n"
"\n"
"/*Border Stuff */\n"
"border: 2px solid rgb(33, 37, 43);\n"
"border-radius: 10px;\n"
"")
        self.TEV_Divide_Radiobutton.setObjectName("TEV_Divide_Radiobutton")
        self.TEV_plot_main_btn = QtWidgets.QPushButton(parent=self.TEV_Main_page)
        self.TEV_plot_main_btn.setGeometry(QtCore.QRect(430, 120, 211, 71))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(13)
        font.setBold(True)
        self.TEV_plot_main_btn.setFont(font)
        self.TEV_plot_main_btn.setStyleSheet("/*Main Text edit Stuff */\n"
"background-color: #FDE38E;\n"
"color: #191818;\n"
"\n"
"/*Font Stuff */\n"
"font-weight: 500px;\n"
"font-family: Verdana;\n"
"\n"
"/*Border Stuff */\n"
"border: 2px solid rgb(33, 37, 43);\n"
"border-radius: 10px;")
        self.TEV_plot_main_btn.setObjectName("TEV_plot_main_btn")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.TEV_Main_page)
        self.scrollArea.setGeometry(QtCore.QRect(20, 240, 1211, 591))
        self.scrollArea.setStyleSheet("\n"
"/*Border Stuff */\n"
"border: 2px solid rgb(33, 37, 43);\n"
"border-radius: 15px;")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1207, 587))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.TEV_equation2_lineEdit = QtWidgets.QLineEdit(parent=self.TEV_Main_page)
        self.TEV_equation2_lineEdit.setGeometry(QtCore.QRect(20, 80, 381, 51))
        self.TEV_equation2_lineEdit.setStyleSheet("/*Main Text edit Stuff */\n"
"background-color: #5B9595;\n"
"color: black;\n"
"\n"
"/*Font Stuff */\n"
"font-weight: 1000px;\n"
"font-size: 21px;\n"
"font-family: Verdana;\n"
"\n"
"/*Border Stuff */\n"
"border: 2px solid rgb(33, 37, 43);\n"
"border-radius: 10px;")
        self.TEV_equation2_lineEdit.setObjectName("TEV_equation2_lineEdit")
        self.TEV_main_background_style_label = QtWidgets.QLabel(parent=self.TEV_Main_page)
        self.TEV_main_background_style_label.setGeometry(QtCore.QRect(0, 220, 1251, 631))
        self.TEV_main_background_style_label.setStyleSheet("/*Main Text edit Stuff */\n"
"background-color: #4C504B;\n"
"color: black;\n"
"\n"
"/*Font Stuff */\n"
"font-weight: 1000px;\n"
"font-size: 18px;\n"
"font-family: Verdana;\n"
"\n"
"/*Border Stuff */\n"
"border: 2px solid rgb(33, 37, 43);\n"
"border-radius: 15px;")
        self.TEV_main_background_style_label.setText("")
        self.TEV_main_background_style_label.setObjectName("TEV_main_background_style_label")
        self.TEV_add_Radiobutton = QtWidgets.QRadioButton(parent=self.TEV_Main_page)
        self.TEV_add_Radiobutton.setGeometry(QtCore.QRect(1160, 160, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(-1)
        font.setBold(True)
        self.TEV_add_Radiobutton.setFont(font)
        self.TEV_add_Radiobutton.setStyleSheet("/*Main Text edit Stuff */\n"
"background-color: #FC3D31;\n"
"color: #1A2329;\n"
"\n"
"/*Font Stuff */\n"
"font-weight: 1000px;\n"
"font-size: 17px;\n"
"font-family: Verdana;\n"
"\n"
"/*Border Stuff */\n"
"border: 2px solid rgb(33, 37, 43);\n"
"border-radius: 10px;\n"
"")
        self.TEV_add_Radiobutton.setObjectName("TEV_add_Radiobutton")
        self.TEV_equation3_lineEdit = QtWidgets.QLineEdit(parent=self.TEV_Main_page)
        self.TEV_equation3_lineEdit.setGeometry(QtCore.QRect(20, 140, 381, 51))
        self.TEV_equation3_lineEdit.setStyleSheet("/*Main Text edit Stuff */\n"
"background-color: #F66545;\n"
"color: black;\n"
"\n"
"/*Font Stuff */\n"
"font-weight: 1000px;\n"
"font-size: 21px;\n"
"font-family: Verdana;\n"
"\n"
"/*Border Stuff */\n"
"border: 2px solid rgb(33, 37, 43);\n"
"border-radius: 10px;")
        self.TEV_equation3_lineEdit.setObjectName("TEV_equation3_lineEdit")
        self.TEV_multiply_Radiobutton = QtWidgets.QRadioButton(parent=self.TEV_Main_page)
        self.TEV_multiply_Radiobutton.setGeometry(QtCore.QRect(1030, 120, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(-1)
        font.setBold(True)
        self.TEV_multiply_Radiobutton.setFont(font)
        self.TEV_multiply_Radiobutton.setStyleSheet("/*Main Text edit Stuff */\n"
"background-color: #F5CD36;\n"
"color: #1A2329;\n"
"\n"
"/*Font Stuff */\n"
"font-weight: 1000px;\n"
"font-size: 17px;\n"
"font-family: Verdana;\n"
"\n"
"/*Border Stuff */\n"
"border: 2px solid rgb(33, 37, 43);\n"
"border-radius: 10px;\n"
"")
        self.TEV_multiply_Radiobutton.setObjectName("TEV_multiply_Radiobutton")
        self.TEV_background_style__equation_label = QtWidgets.QLabel(parent=self.TEV_Main_page)
        self.TEV_background_style__equation_label.setGeometry(QtCore.QRect(10, 10, 401, 191))
        self.TEV_background_style__equation_label.setStyleSheet("/*Main Text edit Stuff */\n"
"background-color: #4C504B;\n"
"color: black;\n"
"\n"
"/*Font Stuff */\n"
"font-weight: 1000px;\n"
"font-size: 18px;\n"
"font-family: Verdana;\n"
"\n"
"/*Border Stuff */\n"
"border: 2px solid rgb(33, 37, 43);\n"
"border-radius: 15px;")
        self.TEV_background_style__equation_label.setText("")
        self.TEV_background_style__equation_label.setObjectName("TEV_background_style__equation_label")
        self.TEV_subtract_Radiobutton = QtWidgets.QRadioButton(parent=self.TEV_Main_page)
        self.TEV_subtract_Radiobutton.setGeometry(QtCore.QRect(1030, 160, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(-1)
        font.setBold(True)
        self.TEV_subtract_Radiobutton.setFont(font)
        self.TEV_subtract_Radiobutton.setStyleSheet("/*Main Text edit Stuff */\n"
"background-color: #F5A436;\n"
"color: #1A2329;\n"
"\n"
"/*Font Stuff */\n"
"font-weight: 1000px;\n"
"font-size: 17px;\n"
"font-family: Verdana;\n"
"\n"
"/*Border Stuff */\n"
"border: 2px solid rgb(33, 37, 43);\n"
"border-radius: 10px;\n"
"")
        self.TEV_subtract_Radiobutton.setObjectName("TEV_subtract_Radiobutton")
        self.TEV_background_style_label = QtWidgets.QLabel(parent=self.TEV_Main_page)
        self.TEV_background_style_label.setGeometry(QtCore.QRect(420, 20, 831, 91))
        self.TEV_background_style_label.setStyleSheet("/*Main Text edit Stuff */\n"
"background-color: #4C504B;\n"
"color: black;\n"
"\n"
"/*Font Stuff */\n"
"font-weight: 1000px;\n"
"font-size: 18px;\n"
"font-family: Verdana;\n"
"\n"
"/*Border Stuff */\n"
"border: 2px solid rgb(33, 37, 43);\n"
"border-radius: 15px;")
        self.TEV_background_style_label.setText("")
        self.TEV_background_style_label.setObjectName("TEV_background_style_label")
        self.TEV_midline_show_checkbox = QtWidgets.QCheckBox(parent=self.TEV_Main_page)
        self.TEV_midline_show_checkbox.setGeometry(QtCore.QRect(1070, 20, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(-1)
        font.setBold(True)
        self.TEV_midline_show_checkbox.setFont(font)
        self.TEV_midline_show_checkbox.setStyleSheet("/*Main Text edit Stuff */\n"
"background-color: #FF6D64;\n"
"color: #1A2329;\n"
"\n"
"/*Font Stuff */\n"
"font-weight: 1000px;\n"
"font-size: 17px;\n"
"font-family: Verdana;\n"
"\n"
"/*Border Stuff */\n"
"border: 2px solid rgb(33, 37, 43);\n"
"border-radius: 10px;\n"
"")
        self.TEV_midline_show_checkbox.setObjectName("TEV_midline_show_checkbox")
        self.TEV_Radians_show_check_box = QtWidgets.QCheckBox(parent=self.TEV_Main_page)
        self.TEV_Radians_show_check_box.setGeometry(QtCore.QRect(1040, 60, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(-1)
        font.setBold(True)
        self.TEV_Radians_show_check_box.setFont(font)
        self.TEV_Radians_show_check_box.setStyleSheet("/*Main Text edit Stuff */\n"
"background-color: #FF6D64;\n"
"color: #1A2329;\n"
"\n"
"/*Font Stuff */\n"
"font-weight: 1000px;\n"
"font-size: 13px;\n"
"font-family: Verdana;\n"
"\n"
"/*Border Stuff */\n"
"border: 2px solid rgb(33, 37, 43);\n"
"border-radius: 10px;\n"
"")
        self.TEV_Radians_show_check_box.setObjectName("TEV_Radians_show_check_box")
        self.TEV_solo_graphing_Radiobutton = QtWidgets.QRadioButton(parent=self.TEV_Main_page)
        self.TEV_solo_graphing_Radiobutton.setGeometry(QtCore.QRect(880, 120, 141, 71))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(-1)
        font.setBold(True)
        self.TEV_solo_graphing_Radiobutton.setFont(font)
        self.TEV_solo_graphing_Radiobutton.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.TEV_solo_graphing_Radiobutton.setStyleSheet("/*Main Text edit Stuff */\n"
"background-color: #FC3D31;\n"
"color: #1A2329;\n"
"\n"
"/*Font Stuff */\n"
"font-weight: 1000px;\n"
"font-size: 14px;\n"
"font-family: Verdana;\n"
"\n"
"/*Border Stuff */\n"
"border: 2px solid rgb(33, 37, 43);\n"
"border-radius: 10px;\n"
"")
        self.TEV_solo_graphing_Radiobutton.setObjectName("TEV_solo_graphing_Radiobutton")
        self.TEV_all_graphs_show_checkbox = QtWidgets.QCheckBox(parent=self.TEV_Main_page)
        self.TEV_all_graphs_show_checkbox.setGeometry(QtCore.QRect(1060, 200, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(-1)
        font.setBold(True)
        self.TEV_all_graphs_show_checkbox.setFont(font)
        self.TEV_all_graphs_show_checkbox.setStyleSheet("/*Main Text edit Stuff */\n"
"background-color: #FF6D64;\n"
"color: #1A2329;\n"
"\n"
"/*Font Stuff */\n"
"font-weight: 1000px;\n"
"font-size: 15px;\n"
"font-family: Verdana;\n"
"\n"
"/*Border Stuff */\n"
"border: 2px solid rgb(33, 37, 43);\n"
"border-radius: 10px;\n"
"")
        self.TEV_all_graphs_show_checkbox.setObjectName("TEV_all_graphs_show_checkbox")
        self.TEV_fix_asymptotes_checkbox = QtWidgets.QCheckBox(parent=self.TEV_Main_page)
        self.TEV_fix_asymptotes_checkbox.setGeometry(QtCore.QRect(700, 200, 351, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(-1)
        font.setBold(True)
        self.TEV_fix_asymptotes_checkbox.setFont(font)
        self.TEV_fix_asymptotes_checkbox.setStyleSheet("/*Main Text edit Stuff */\n"
"background-color: #FF6D64;\n"
"color: #1A2329;\n"
"\n"
"/*Font Stuff */\n"
"font-weight: 1000px;\n"
"font-size: 15px;\n"
"font-family: Verdana;\n"
"\n"
"/*Border Stuff */\n"
"border: 2px solid rgb(33, 37, 43);\n"
"border-radius: 10px;\n"
"")
        self.TEV_fix_asymptotes_checkbox.setChecked(True)
        self.TEV_fix_asymptotes_checkbox.setObjectName("TEV_fix_asymptotes_checkbox")
        self.TEV_background_style_label.raise_()
        self.TEV_main_background_style_label.raise_()
        self.TEV_background_style__equation_label.raise_()
        self.TEV_title_label.raise_()
        self.TEV_equation1_lineEdit.raise_()
        self.TEV_background_style_btn_label.raise_()
        self.TEV_help_btn.raise_()
        self.TEV_Divide_Radiobutton.raise_()
        self.TEV_plot_main_btn.raise_()
        self.scrollArea.raise_()
        self.TEV_equation2_lineEdit.raise_()
        self.TEV_add_Radiobutton.raise_()
        self.TEV_equation3_lineEdit.raise_()
        self.TEV_multiply_Radiobutton.raise_()
        self.TEV_subtract_Radiobutton.raise_()
        self.TEV_midline_show_checkbox.raise_()
        self.TEV_Radians_show_check_box.raise_()
        self.TEV_solo_graphing_Radiobutton.raise_()
        self.TEV_all_graphs_show_checkbox.raise_()
        self.TEV_fix_asymptotes_checkbox.raise_()
        self.TEV_stackedWidget.addWidget(self.TEV_Main_page)
        self.TEV_help_page = QtWidgets.QWidget()
        self.TEV_help_page.setObjectName("TEV_help_page")
        self.TEV_background_help_menu_label_2 = QtWidgets.QLabel(parent=self.TEV_help_page)
        self.TEV_background_help_menu_label_2.setGeometry(QtCore.QRect(0, 0, 401, 851))
        self.TEV_background_help_menu_label_2.setStyleSheet("/*Main Text edit Stuff */\n"
"background-color: #4C504B;\n"
"color: black;\n"
"\n"
"/*Font Stuff */\n"
"font-weight: 1000px;\n"
"font-size: 18px;\n"
"font-family: Verdana;\n"
"\n"
"/*Border Stuff */\n"
"border: 2px solid rgb(33, 37, 43);\n"
"border-radius: 15px;")
        self.TEV_background_help_menu_label_2.setText("")
        self.TEV_background_help_menu_label_2.setObjectName("TEV_background_help_menu_label_2")
        self.TEV_background_help_menu_label_3 = QtWidgets.QLabel(parent=self.TEV_help_page)
        self.TEV_background_help_menu_label_3.setGeometry(QtCore.QRect(420, 0, 401, 851))
        self.TEV_background_help_menu_label_3.setStyleSheet("/*Main Text edit Stuff */\n"
"background-color: #4C504B;\n"
"color: black;\n"
"\n"
"/*Font Stuff */\n"
"font-weight: 1000px;\n"
"font-size: 18px;\n"
"font-family: Verdana;\n"
"\n"
"/*Border Stuff */\n"
"border: 2px solid rgb(33, 37, 43);\n"
"border-radius: 15px;")
        self.TEV_background_help_menu_label_3.setText("")
        self.TEV_background_help_menu_label_3.setObjectName("TEV_background_help_menu_label_3")
        self.TEV_background_help_menu_label_1 = QtWidgets.QLabel(parent=self.TEV_help_page)
        self.TEV_background_help_menu_label_1.setGeometry(QtCore.QRect(840, 0, 411, 851))
        self.TEV_background_help_menu_label_1.setStyleSheet("/*Main Text edit Stuff */\n"
"background-color: #4C504B;\n"
"color: black;\n"
"\n"
"/*Font Stuff */\n"
"font-weight: 1000px;\n"
"font-size: 18px;\n"
"font-family: Verdana;\n"
"\n"
"/*Border Stuff */\n"
"border: 2px solid rgb(33, 37, 43);\n"
"border-radius: 15px;")
        self.TEV_background_help_menu_label_1.setText("")
        self.TEV_background_help_menu_label_1.setObjectName("TEV_background_help_menu_label_1")
        self.TEV_background_help_menu_label_4 = QtWidgets.QLabel(parent=self.TEV_help_page)
        self.TEV_background_help_menu_label_4.setGeometry(QtCore.QRect(10, 0, 401, 851))
        self.TEV_background_help_menu_label_4.setStyleSheet("/*Main Text edit Stuff */\n"
"background-color: #507A3A;\n"
"color: black;\n"
"\n"
"/*Font Stuff */\n"
"font-weight: 1000px;\n"
"font-size: 21px;\n"
"font-family: Verdana;\n"
"\n"
"/*Border Stuff */\n"
"border: 2px solid rgb(33, 37, 43);\n"
"border-radius: 10px;")
        self.TEV_background_help_menu_label_4.setText("")
        self.TEV_background_help_menu_label_4.setObjectName("TEV_background_help_menu_label_4")
        self.TEV_background_style_btn_label_5 = QtWidgets.QLabel(parent=self.TEV_help_page)
        self.TEV_background_style_btn_label_5.setGeometry(QtCore.QRect(430, 0, 401, 851))
        self.TEV_background_style_btn_label_5.setStyleSheet("/*Main Text edit Stuff */\n"
"background-color: #5B754C;\n"
"color: black;\n"
"\n"
"/*Font Stuff */\n"
"font-weight: 1000px;\n"
"font-size: 21px;\n"
"font-family: Verdana;\n"
"\n"
"/*Border Stuff */\n"
"border: 2px solid rgb(33, 37, 43);\n"
"border-radius: 10px;")
        self.TEV_background_style_btn_label_5.setText("")
        self.TEV_background_style_btn_label_5.setObjectName("TEV_background_style_btn_label_5")
        self.TEV_background_style_btn_label_6 = QtWidgets.QLabel(parent=self.TEV_help_page)
        self.TEV_background_style_btn_label_6.setGeometry(QtCore.QRect(850, 0, 401, 851))
        self.TEV_background_style_btn_label_6.setStyleSheet("/*Main Text edit Stuff */\n"
"background-color: #6B8E57;\n"
"color: black;\n"
"\n"
"/*Font Stuff */\n"
"font-weight: 1000px;\n"
"font-size: 21px;\n"
"font-family: Verdana;\n"
"\n"
"/*Border Stuff */\n"
"border: 2px solid rgb(33, 37, 43);\n"
"border-radius: 10px;")
        self.TEV_background_style_btn_label_6.setText("")
        self.TEV_background_style_btn_label_6.setObjectName("TEV_background_style_btn_label_6")
        self.TEV_Main_helptitle_label = QtWidgets.QLabel(parent=self.TEV_help_page)
        self.TEV_Main_helptitle_label.setGeometry(QtCore.QRect(440, 30, 371, 51))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(True)
        self.TEV_Main_helptitle_label.setFont(font)
        self.TEV_Main_helptitle_label.setStyleSheet("/*Main Text edit Stuff */\n"
"background-color: #C44848;\n"
"color: #1A2329;\n"
"\n"
"/*Font Stuff */\n"
"font-weight: 1000px;\n"
"font-size: 21px;\n"
"font-family: Verdana;\n"
"\n"
"/*Border Stuff */\n"
"border: 2px solid rgb(33, 37, 43);\n"
"border-radius: 10px;")
        self.TEV_Main_helptitle_label.setObjectName("TEV_Main_helptitle_label")
        self.TEV_help_subtitle1_label = QtWidgets.QLabel(parent=self.TEV_help_page)
        self.TEV_help_subtitle1_label.setGeometry(QtCore.QRect(20, 30, 371, 51))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(True)
        self.TEV_help_subtitle1_label.setFont(font)
        self.TEV_help_subtitle1_label.setStyleSheet("/*Main Text edit Stuff */\n"
"background-color: #B56A6A;\n"
"color: #1A2329;\n"
"\n"
"/*Font Stuff */\n"
"font-weight: 1000px;\n"
"font-size: 21px;\n"
"font-family: Verdana;\n"
"\n"
"/*Border Stuff */\n"
"border: 2px solid rgb(33, 37, 43);\n"
"border-radius: 10px;")
        self.TEV_help_subtitle1_label.setObjectName("TEV_help_subtitle1_label")
        self.TEVL_help_body1 = QtWidgets.QTextEdit(parent=self.TEV_help_page)
        self.TEVL_help_body1.setGeometry(QtCore.QRect(30, 90, 361, 731))
        self.TEVL_help_body1.setStyleSheet("/*Main Text edit Stuff */\n"
"background-color: #D2D16E;\n"
"color: #1A2329;\n"
"\n"
"/*Font Stuff */\n"
"font-weight: 1000px;\n"
"font-size: 21px;\n"
"font-family: Verdana;\n"
"\n"
"/*Border Stuff */\n"
"border: 2px solid rgb(33, 37, 43);\n"
"border-radius: 10px;")
        self.TEVL_help_body1.setReadOnly(True)
        self.TEVL_help_body1.setObjectName("TEVL_help_body1")
        self.TEVL_help_body2 = QtWidgets.QTextEdit(parent=self.TEV_help_page)
        self.TEVL_help_body2.setGeometry(QtCore.QRect(450, 180, 361, 641))
        self.TEVL_help_body2.setStyleSheet("/*Main Text edit Stuff */\n"
"background-color: #D2D16E;\n"
"color: #1A2329;\n"
"\n"
"/*Font Stuff */\n"
"font-weight: 1000px;\n"
"font-size: 21px;\n"
"font-family: Verdana;\n"
"\n"
"/*Border Stuff */\n"
"border: 2px solid rgb(33, 37, 43);\n"
"border-radius: 10px;")
        self.TEVL_help_body2.setReadOnly(True)
        self.TEVL_help_body2.setObjectName("TEVL_help_body2")
        self.TEV_help_subtitle2_Textedit = QtWidgets.QTextEdit(parent=self.TEV_help_page)
        self.TEV_help_subtitle2_Textedit.setGeometry(QtCore.QRect(450, 110, 361, 61))
        self.TEV_help_subtitle2_Textedit.setStyleSheet("/*Main Text edit Stuff */\n"
"background-color: #B56A6A;\n"
"color: #1A2329;\n"
"\n"
"/*Font Stuff */\n"
"font-weight: 1000px;\n"
"font-size: 21px;\n"
"font-family: Verdana;\n"
"\n"
"/*Border Stuff */\n"
"border: 2px solid rgb(33, 37, 43);\n"
"border-radius: 10px;")
        self.TEV_help_subtitle2_Textedit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.TEV_help_subtitle2_Textedit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.TEV_help_subtitle2_Textedit.setReadOnly(True)
        self.TEV_help_subtitle2_Textedit.setObjectName("TEV_help_subtitle2_Textedit")
        self.TEV_help_subtitle3_textedit = QtWidgets.QTextEdit(parent=self.TEV_help_page)
        self.TEV_help_subtitle3_textedit.setGeometry(QtCore.QRect(860, 30, 381, 71))
        self.TEV_help_subtitle3_textedit.setStyleSheet("/*Main Text edit Stuff */\n"
"background-color: #B56A6A;\n"
"color: #1A2329;\n"
"\n"
"/*Font Stuff */\n"
"font-weight: 1000px;\n"
"font-size: 21px;\n"
"font-family: Verdana;\n"
"\n"
"/*Border Stuff */\n"
"border: 2px solid rgb(33, 37, 43);\n"
"border-radius: 10px;")
        self.TEV_help_subtitle3_textedit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.TEV_help_subtitle3_textedit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.TEV_help_subtitle3_textedit.setReadOnly(True)
        self.TEV_help_subtitle3_textedit.setObjectName("TEV_help_subtitle3_textedit")
        self.TEVL_help_body3 = QtWidgets.QTextEdit(parent=self.TEV_help_page)
        self.TEVL_help_body3.setGeometry(QtCore.QRect(860, 110, 381, 641))
        self.TEVL_help_body3.setStyleSheet("/*Main Text edit Stuff */\n"
"background-color: #D2D16E;\n"
"color: #1A2329;\n"
"\n"
"/*Font Stuff */\n"
"font-weight: 1000px;\n"
"font-size: 21px;\n"
"font-family: Verdana;\n"
"\n"
"/*Border Stuff */\n"
"border: 2px solid rgb(33, 37, 43);\n"
"border-radius: 10px;")
        self.TEVL_help_body3.setReadOnly(True)
        self.TEVL_help_body3.setObjectName("TEVL_help_body3")
        self.TEV_go_graphing_page_btn = QtWidgets.QPushButton(parent=self.TEV_help_page)
        self.TEV_go_graphing_page_btn.setGeometry(QtCore.QRect(850, 770, 401, 81))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(-1)
        font.setBold(True)
        self.TEV_go_graphing_page_btn.setFont(font)
        self.TEV_go_graphing_page_btn.setStyleSheet("/*Main Text edit Stuff */\n"
"background-color: #6C84E8;\n"
"color: #1A2329;\n"
"\n"
"/*Font Stuff */\n"
"font-weight: 1000px;\n"
"font-size: 20px;\n"
"font-family: Verdana;\n"
"\n"
"/*Border Stuff */\n"
"border: 2px solid rgb(33, 37, 43);\n"
"border-radius: 10px;")
        self.TEV_go_graphing_page_btn.setObjectName("TEV_go_graphing_page_btn")
        self.TEV_stackedWidget.addWidget(self.TEV_help_page)
        Trigonometry_Equation_Visualizer.setCentralWidget(self.TEV_main_centeral_widget)

        self.retranslateUi(Trigonometry_Equation_Visualizer)
        self.TEV_stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Trigonometry_Equation_Visualizer)

    def retranslateUi(self, Trigonometry_Equation_Visualizer):
        _translate = QtCore.QCoreApplication.translate
        Trigonometry_Equation_Visualizer.setWindowTitle(_translate("Trigonometry_Equation_Visualizer", "Trigonometry Equation Visualizer"))
        self.TEV_title_label.setText(_translate("Trigonometry_Equation_Visualizer", "Elijah Sayres: Trigonometry Equation Visualizer"))
        self.TEV_equation1_lineEdit.setPlaceholderText(_translate("Trigonometry_Equation_Visualizer", "Equation 1"))
        self.TEV_help_btn.setText(_translate("Trigonometry_Equation_Visualizer", "Click For Help Button!"))
        self.TEV_Divide_Radiobutton.setText(_translate("Trigonometry_Equation_Visualizer", "Divide"))
        self.TEV_plot_main_btn.setText(_translate("Trigonometry_Equation_Visualizer", "Plot Button!"))
        self.TEV_equation2_lineEdit.setPlaceholderText(_translate("Trigonometry_Equation_Visualizer", "Equation 2"))
        self.TEV_add_Radiobutton.setText(_translate("Trigonometry_Equation_Visualizer", "Add"))
        self.TEV_equation3_lineEdit.setPlaceholderText(_translate("Trigonometry_Equation_Visualizer", "Equation 3"))
        self.TEV_multiply_Radiobutton.setText(_translate("Trigonometry_Equation_Visualizer", "Multiply"))
        self.TEV_subtract_Radiobutton.setText(_translate("Trigonometry_Equation_Visualizer", "Subtract"))
        self.TEV_midline_show_checkbox.setText(_translate("Trigonometry_Equation_Visualizer", "Show Midlines?"))
        self.TEV_Radians_show_check_box.setText(_translate("Trigonometry_Equation_Visualizer", "Show Radians Symbols?"))
        self.TEV_solo_graphing_Radiobutton.setText(_translate("Trigonometry_Equation_Visualizer", "Solo Graphing"))
        self.TEV_all_graphs_show_checkbox.setText(_translate("Trigonometry_Equation_Visualizer", "Show All Graphs?"))
        self.TEV_fix_asymptotes_checkbox.setText(_translate("Trigonometry_Equation_Visualizer", "Attempt To Fix Vertical Asymptotes?"))
        self.TEV_Main_helptitle_label.setText(_translate("Trigonometry_Equation_Visualizer", "                 Help Page"))
        self.TEV_help_subtitle1_label.setText(_translate("Trigonometry_Equation_Visualizer", "           How To Graph?"))
        self.TEVL_help_body1.setHtml(_translate("Trigonometry_Equation_Visualizer", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Verdana\'; font-size:21px; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:21px;\">To start </span><span style=\" font-size:21px; font-weight:700; text-decoration: underline;\">graphing</span><span style=\" font-size:21px;\"> some equations!</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:21px;\">you\'ll need a </span><span style=\" font-size:21px; font-style:italic; text-decoration: underline;\">sinusoidal equation</span><span style=\" font-size:21px;\"> that looks something like:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:21px;\"> </span><span style=\" font-size:21px; font-weight:700; font-style:italic; text-decoration: underline;\">Asin(K</span><span style=\" font-size:21px; font-weight:700; font-style:italic; text-decoration: underline; color:#000000;\">(x </span><a href=\"https://www.google.com/url?sa=t&amp;rct=j&amp;q=&amp;esrc=s&amp;source=web&amp;cd=&amp;ved=2ahUKEwiDh4iO04CAAxVCKEQIHdHXAoQQFnoECCQQAQ&amp;url=https%3A%2F%2Fwumbo.net%2Fsymbols%2Fplus-minus%2F&amp;usg=AOvVaw1NqRJuvX__-Yz-yKxl7V_i&amp;opi=89978449\"><span style=\" font-family:\'Roboto\',\'arial\',\'sans-serif\'; font-size:large; font-weight:700; font-style:italic; text-decoration: underline; color:#000000;\">± C</span></a><span style=\" font-size:21px; font-weight:700; font-style:italic; text-decoration: underline; color:#000000;\">)</span><span style=\" font-size:21px; font-weight:700; font-style:italic; text-decoration: underline;\">)</span><a href=\"https://www.google.com/url?sa=t&amp;rct=j&amp;q=&amp;esrc=s&amp;source=web&amp;cd=&amp;ved=2ahUKEwiDh4iO04CAAxVCKEQIHdHXAoQQFnoECCQQAQ&amp;url=https%3A%2F%2Fwumbo.net%2Fsymbols%2Fplus-minus%2F&amp;usg=AOvVaw1NqRJuvX__-Yz-yKxl7V_i&amp;opi=89978449\"><span style=\" font-family:\'Roboto\',\'arial\',\'sans-serif\'; font-size:large; font-weight:700; font-style:italic; text-decoration: underline; color:#000000;\">±</span></a><span style=\" font-size:21px; font-weight:700; font-style:italic; text-decoration: underline;\">B</span><span style=\" font-size:21px;\">. </span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:21px;\">or a equation that looks similar to this:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:21px;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:21px; font-weight:700; font-style:italic; text-decoration: underline;\">Constant = Asin(K</span><span style=\" font-size:21px; font-weight:700; font-style:italic; text-decoration: underline; color:#000000;\">(x </span><a href=\"https://www.google.com/url?sa=t&amp;rct=j&amp;q=&amp;esrc=s&amp;source=web&amp;cd=&amp;ved=2ahUKEwiDh4iO04CAAxVCKEQIHdHXAoQQFnoECCQQAQ&amp;url=https%3A%2F%2Fwumbo.net%2Fsymbols%2Fplus-minus%2F&amp;usg=AOvVaw1NqRJuvX__-Yz-yKxl7V_i&amp;opi=89978449\"><span style=\" font-family:\'Roboto\',\'arial\',\'sans-serif\'; font-size:large; font-weight:700; font-style:italic; text-decoration: underline; color:#000000;\">± </span></a><span style=\" font-size:21px; font-weight:700; font-style:italic; text-decoration: underline; color:#000000;\">C)</span><span style=\" font-size:21px; font-weight:700; font-style:italic; text-decoration: underline;\">)</span><a href=\"https://www.google.com/url?sa=t&amp;rct=j&amp;q=&amp;esrc=s&amp;source=web&amp;cd=&amp;ved=2ahUKEwiDh4iO04CAAxVCKEQIHdHXAoQQFnoECCQQAQ&amp;url=https%3A%2F%2Fwumbo.net%2Fsymbols%2Fplus-minus%2F&amp;usg=AOvVaw1NqRJuvX__-Yz-yKxl7V_i&amp;opi=89978449\"><span style=\" font-family:\'Roboto\',\'arial\',\'sans-serif\'; font-size:large; font-weight:700; font-style:italic; text-decoration: underline; color:#000000;\">±</span></a><span style=\" font-size:21px; font-weight:700; font-style:italic; text-decoration: underline;\">B</span><span style=\" font-size:21px;\">.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:21px;\">You then can type the equation into any of the </span><span style=\" font-size:21px; font-weight:700; font-style:italic; text-decoration: underline;\">3 boxes</span><span style=\" font-size:21px;\"> on the </span><span style=\" font-size:21px; font-weight:700; font-style:italic; text-decoration: underline;\">top left</span><span style=\" font-size:21px;\"> of the screen.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; text-decoration: underline;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:21px;\">Then you click the big yellow Plot button to have your equations graphed onto the screen!</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:21px;\">Supports Writting Equations </span><span style=\" font-size:16pt;\">using </span><span style=\" font-size:16pt; font-weight:700;\">Pi</span><span style=\" font-size:16pt;\"> o</span><span style=\" font-size:16pt; color:#000000;\">r</span><span style=\" font-size:16pt; font-weight:700; color:#000000;\"> </span><span style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:16pt; font-weight:700; font-style:italic; color:#000000;\">π </span><span style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:16pt; color:#000000;\">and using decimals or Fractions (like 1/2 or 0.5) in Equation writing. </span><span style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:16pt; font-weight:700; font-style:italic; color:#000000;\">( pi/4 sin( 2pi/4 (x+ 42/4 )) + 2.5 )</span><span style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:16pt; color:#000000;\"> </span><span style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:16pt; font-style:italic; text-decoration: underline; color:#000000;\">will Plot a valid Graph!</span><span style=\" font-size:16pt; font-style:italic; text-decoration: underline;\"><br /></span></p></body></html>"))
        self.TEVL_help_body2.setHtml(_translate("Trigonometry_Equation_Visualizer", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Verdana\'; font-size:21px; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:21px;\">If you want to </span><span style=\" font-size:21px; font-weight:700; font-style:italic; text-decoration: underline;\">Add, Subtract, Multiply, or Divide any 2 - 3 equations</span><span style=\" font-size:21px;\"> together and have them graphed you can!</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:21px;\">for example if you wanted to add:<br /> </span><span style=\" font-size:21px; font-weight:700; font-style:italic; text-decoration: underline;\">Asin(K</span><span style=\" font-size:21px; font-weight:700; font-style:italic; text-decoration: underline; color:#000000;\">(x))</span><span style=\" font-size:21px; font-weight:700; font-style:italic; text-decoration: underline;\"> + Acos(K(x))</span><span style=\" font-size:21px;\">.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:21px;\"><br />you would write the equations into the boxes </span><span style=\" font-size:21px; font-weight:700; font-style:italic; text-decoration: underline;\">Seperately</span><span style=\" font-size:21px;\">. </span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:21px;\">Then you would click any of the </span><span style=\" font-size:21px; font-weight:700; font-style:italic; text-decoration: underline;\">4 Radio button</span><span style=\" font-size:21px;\"> on the far right of the screen that are titled (</span><span style=\" font-size:21px; font-weight:700; font-style:italic; text-decoration: underline;\">Add, Multiply, Divide, Subtract</span><span style=\" font-size:21px;\">) accordingly.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:21px;\">Finally you would click the Plot Button!</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:21px;\">Click the </span><span style=\" font-size:21px; font-style:italic; text-decoration: underline;\">Fix Vertical asymptotes</span><span style=\" font-size:21px;\"> button to </span><span style=\" font-size:21px; font-style:italic; text-decoration: underline;\">attempt to get rid</span><span style=\" font-size:21px;\"> of any connecting asympotes from ploting with </span><span style=\" font-size:21px; font-style:italic; text-decoration: underline;\">tan</span></p></body></html>"))
        self.TEV_help_subtitle2_Textedit.setHtml(_translate("Trigonometry_Equation_Visualizer", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Verdana\'; font-size:21px; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:700;\">Add, Multiply, Divide, Subtract Several Equations!</span></p></body></html>"))
        self.TEV_help_subtitle3_textedit.setHtml(_translate("Trigonometry_Equation_Visualizer", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Verdana\'; font-size:21px; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; font-weight:700;\">Tools to know about on Graph!</span></p></body></html>"))
        self.TEVL_help_body3.setHtml(_translate("Trigonometry_Equation_Visualizer", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Verdana\'; font-size:21px; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:21px;\">when interacting with the graph you can click the </span><span style=\" font-size:21px; font-weight:700; font-style:italic; text-decoration: underline;\">4 crosses Icon</span><span style=\" font-size:21px;\"> </span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:21px;\">   To move around the graph with </span><span style=\" font-size:21px; font-style:italic; text-decoration: underline;\">Left Click and Hold.</span><span style=\" font-size:21px;\"> </span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:21px;\">   </span><span style=\" font-size:21px; font-style:italic; text-decoration: underline;\">Right Click and Hold</span><span style=\" font-size:21px;\"> will Strech the Graph around.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:21px;\">the </span><span style=\" font-size:21px; font-weight:700; font-style:italic; text-decoration: underline;\">Magnifying Glass Icon</span><span style=\" font-size:21px;\"> will let you Zoom in with </span><span style=\" font-size:21px; font-style:italic; text-decoration: underline;\">Left Click and drag</span><span style=\" font-size:21px;\">.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:21px;\">   </span><span style=\" font-size:21px; font-style:italic; text-decoration: underline;\">Right Click and drag</span><span style=\" font-size:21px;\"> to Zoom out.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:21px;\">The </span><span style=\" font-size:21px; font-weight:700; font-style:italic; text-decoration: underline;\">Floppy Disk Icon</span><span style=\" font-size:21px;\"> will let you Save a image of the Graph to your Desktop to view later on!</span></p></body></html>"))
        self.TEV_go_graphing_page_btn.setText(_translate("Trigonometry_Equation_Visualizer", "PRESS TO START GRAPHING!"))
